### ISSUE TITLE
V1 & Open Source

### ISSUE THREAD

**Issue by KAVA-Leigh** [navilang/navi#4]
The language is looking great & after the recent release, is there any timeline for v1.0? 

Also, is there any update as to open sourcing ?

**Comment by huacnlee** [comment]
The current focus of Navi is to improve our internal system at [Longbridge](https://github.com/longportapp).

There are still many tasks pending, preventing us from releasing Navi. In fact, we have not made any announcements about Navi on our social media accounts.

For example:

- The majority of Navi's librariesis are written in Rust (> 80%)
- No package management, it's hard to extend.
- The performance is not good enough.
- Compared with other languages, Navi does not stand out.

We have had numerous discussions about when to release Navi, we know that Navi have no outstanding advantages of the other language (In currently).

If we are eager to release it, that will fail in quickly. (There are a lot of cases).

Make Navi a popular language is not our goal in currently, this is a long-term goal, so we are focusing on making Navi good in some specific areas.

----

But, if you are interested in Navi, you can try it out now. The latest version of Navi is more stable than before, We have controlled the breaking changes. Additionally, with each version release, I will provide a changelog. The tools and documentation for Navi are readily available.
