### ISSUE TITLE
Feature: StringBuilder / stringstream

### ISSUE THREAD

**Issue by KieranP** [navilang/navi#9]
A way to efficiently build strings. Current options include concatening string or building string array and calling `join('')`, neither of which is performant:

C#
```c#
var rendering = new StringBuilder();
for (var y = 0; y < height; y++) {
  for (var x = 0; x < width; x++) {
    var cell = cell_at(x, y);
    rendering.Append(cell.to_char());
  }
  rendering.Append("\n");
}
return rendering.ToString();
```

C++
```c++
stringstream rendering;
for (auto y = 0; y < height; y++) {
  for (auto x = 0; x < width; x++) {
    auto cell = *cell_at(x, y);
    rendering << cell->to_char();
  }
  rendering << "\n";
}
return rendering.str();
```

GoLang:
```go
rendering := strings.Builder{}
rendering.Grow(world.width * world.height)
for y := range(world.height) {
	for x := range(world.width) {
		cell, _ := world.cell_at(x, y)
		rendering.WriteRune(cell.to_char())
	}
	rendering.WriteRune('\n')
}
return rendering.String()
```

**Comment by sunli829** [comment]
For string concatenation, navi is optimized internally and does not need to copy the entire string, so StringBuilder is not needed.

**Comment by KieranP** [comment]
@sunli829 Ok, thank you. Is there a more efficient way to do this then?

```navi
    let rendering: [string] = [];
    for (let y in 0..self.height) {
      for (let x in 0..self.width) {
        let cell = self.cell_at(x, y);
        if (!cell.is_nil()) {
          rendering.push(cell!.to_char().to_string());
        }
      }
      rendering.push("\n");
    }
    return rendering.join("");
```

I have a Cell struct, with a to_char() method. It returns a `char`. But because there is no such thing as `[Char].join()` (it only works with `[String].join()`, I have to call to_string() on each char within the loop, which I think might be slowing things down? Any thoughts?

**Comment by sunli829** [comment]
I will add `[char].join()` method

**Comment by KieranP** [comment]
Going to mark this as closed as it looks like StringBuffer has been added in a recent version:
https://navi-lang.org/stdlib/std.str.StringBuffer
